<!doctype html>
<html lang="">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    Hello, world!
    <div>
        <form method="post">
            <input type="text" name="name" placeholder="Name">
            <input type="email" name="mail" placeholder="Mail">
            <input type="submit" value="Войти">
        </form>
    </div>
</body>
</html>